### ISSUE TITLE
generate_proto_stubs.sh seems broken

### ISSUE THREAD

**Issue by amin2718** [vectara/getting-started#29] opened 2024-02-27 16:09 UTC
### File

generate_proto_stubs.sh

### Description

When I run a Python program, I get the following error:

```
Traceback (most recent call last):
  File "/home/amin/clients/zir/amin/juniper-upload/index_juniper_docs.py", line 10, in <module>
    import services_pb2_grpc
  File "/home/amin/clients/zir/amin/juniper-upload/services_pb2_grpc.py", line 5, in <module>
    import admin_account_pb2 as admin__account__pb2
ModuleNotFoundError: No module named 'admin_account_pb2'
```

It seems like `generate_proto_stubs.sh` isn't actually building the complete set of protos:

```
python3 -m grpc_tools.protoc -I=./protos/ -I=${EXROOT} --python_out=. --grpc_python_out=. \
    admin.proto \
    common.proto \
    custom_dim.proto \
    indexing.proto \
    services.proto \
    serving.proto \
    status.proto \
    protoc-gen-openapiv2/options/annotations.proto \
    protoc-gen-openapiv2/options/openapiv2.proto
```

**Comment by amin2718** [comment] 2024-02-27 16:10
Tallat, I assigned to you for triage. Some kind of automated test would probably make sense.

**Comment by tallatshafaat** [comment] 2024-02-27 22:20
Thanks Amin.
Laurence is going to take care of this, and then add an automated test as well with the help of Srinivas. We had aimed to add automated tests earlier, but that didn't work out.

**Comment by lgoodby** [comment] 2024-03-04 16:26
Running generate_proto_stubs.sh requires that grpcio-tools be installed. This will happen automatically using the procedure documented in the python/vectara-grpc/README.md:

- Create a Python virtual environment following the steps in the README.
- Install the Python dependencies using `pip3 install -r requirements.txt`, as described in the README.
- Run `generate_proto_stubs.sh`.

**Comment by lgoodby** [comment] 2024-03-04 16:29
Closing this as working as intended.

**Comment by Tonymzaramo** [comment] 2024-04-19 01:07
Traceback (most recent call last):
  File "/home/amin/clients/zir/amin/juniper-upload/index_juniper_docs.py", line 10, in <module>
    import services_pb2_grpc
  File "/home/amin/clients/zir/amin/juniper-upload/services_pb2_grpc.py", line 5, in <module>
    import admin_account_pb2 as admin__account__pb2
ModuleNotFoundError: No module named 'admin_account_pb2'

**Comment by lgoodby** [comment] 2024-04-19 17:39
Should be fixed by https://github.com/vectara/getting-started/pull/30

**Comment by lgoodby** [comment] 2024-04-19 17:41
Closing.

**Closed by lgoodby** 2024-04-19 17:41 UTC
Labels: bug
